client_body_temp_path  /tmp/nginx/body;
proxy_temp_path        /tmp/nginx/proxy;
fastcgi_temp_path      /tmp/nginx/fastcgi;
uwsgi_temp_path        /tmp/nginx/uwsgi;
scgi_temp_path         /tmp/nginx/scgi;
